# Generated by Django 2.0.dev20170508173203 on 2017-06-14 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virusTotal_rate', models.CharField(max_length=255, null=True)),
                ('deepAnalyser_rate', models.CharField(max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_upload.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Document_fingerPrints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(max_length=255, null=True)),
                ('sha256', models.CharField(max_length=255, null=True)),
                ('md5', models.CharField(max_length=255, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_upload.Document')),
            ],
        ),
    ]
